### PR TITLE
[TASK] Adding german translations

### PR DESCRIPTION
**Pull request by opptor**
Hi, 

thanks for this extension, it helped me a lot. I created some german translations for it.

### CODE REVIEW

**Comment by codesource** [comment]
Thanks for your contribution.
I have to do some improvement in template selection before merging your pull request.
I want to keep English version :)

**Comment by ckrrtp** [comment]
Please do not simply replace the English texts with another language. The whole template must be overwritable and the texts must come from a project specific LL-file. 

That's the only clean way, cheers.

**Comment by codesource** [comment]
You are right.
Default template selection will take care of be-user language selection.

Edit: I will do the change later, need to figure how to do it cleanly

**Comment by opptor** [comment]
Hi,

thanks for your feedback. I just needed a quick german template an forgot totally about my pull request. I will implement this cleanly pretty soon :)

Cheers

**Pull request merged**
